# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(491, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 471, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.FileOperationsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.FileOperationsLayout.setContentsMargins(0, 0, 0, 0)
        self.FileOperationsLayout.setObjectName("FileOperationsLayout")
        self.Path_start_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Path_start_label.setFont(font)
        self.Path_start_label.setObjectName("Path_start_label")
        self.FileOperationsLayout.addWidget(self.Path_start_label)
        self.FileInputLayout = QtWidgets.QHBoxLayout()
        self.FileInputLayout.setObjectName("FileInputLayout")
        self.File_url_input = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.File_url_input.setMinimumSize(QtCore.QSize(0, 0))
        self.File_url_input.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.File_url_input.setFont(font)
        self.File_url_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.File_url_input.setObjectName("File_url_input")
        self.FileInputLayout.addWidget(self.File_url_input)
        self.File_input_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.File_input_button.setFont(font)
        self.File_input_button.setAutoFillBackground(False)
        self.File_input_button.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.File_input_button.setObjectName("File_input_button")
        self.FileInputLayout.addWidget(self.File_input_button)
        self.FileOperationsLayout.addLayout(self.FileInputLayout)
        self.Path_result_lable = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Path_result_lable.setFont(font)
        self.Path_result_lable.setObjectName("Path_result_lable")
        self.FileOperationsLayout.addWidget(self.Path_result_lable)
        self.FileOutputLayout = QtWidgets.QHBoxLayout()
        self.FileOutputLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.FileOutputLayout.setContentsMargins(0, -1, -1, -1)
        self.FileOutputLayout.setSpacing(6)
        self.FileOutputLayout.setObjectName("FileOutputLayout")
        self.File_url_output = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.File_url_output.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.File_url_output.setFont(font)
        self.File_url_output.setObjectName("File_url_output")
        self.FileOutputLayout.addWidget(self.File_url_output)
        self.File_output_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.File_output_button.setFont(font)
        self.File_output_button.setAutoFillBackground(False)
        self.File_output_button.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.File_output_button.setObjectName("File_output_button")
        self.FileOutputLayout.addWidget(self.File_output_button)
        self.FileOperationsLayout.addLayout(self.FileOutputLayout)
        self.Label_filename_output = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_filename_output.setFont(font)
        self.Label_filename_output.setObjectName("Label_filename_output")
        self.FileOperationsLayout.addWidget(self.Label_filename_output)
        self.Edit_filename_output = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.Edit_filename_output.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Edit_filename_output.setFont(font)
        self.Edit_filename_output.setObjectName("Edit_filename_output")
        self.FileOperationsLayout.addWidget(self.Edit_filename_output)
        self.Calculate_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.Calculate_button.setObjectName("Calculate_button")
        self.FileOperationsLayout.addWidget(self.Calculate_button)
        self.Finish_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Finish_label.setFont(font)
        self.Finish_label.setStyleSheet("color: rgb(0, 170, 0);")
        self.Finish_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Finish_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Finish_label.setLineWidth(1)
        self.Finish_label.setObjectName("Finish_label")
        self.FileOperationsLayout.addWidget(self.Finish_label)
        self.ProblemsBoxLayout = QtWidgets.QVBoxLayout()
        self.ProblemsBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ProblemsBoxLayout.setContentsMargins(0, 0, -1, 6)
        self.ProblemsBoxLayout.setObjectName("ProblemsBoxLayout")
        self.Problems_text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_4)
        self.Problems_text.setEnabled(True)
        self.Problems_text.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Problems_text.setFont(font)
        self.Problems_text.setObjectName("Problems_text")
        self.ProblemsBoxLayout.addWidget(self.Problems_text)
        self.FileOperationsLayout.addLayout(self.ProblemsBoxLayout)
        self.Author_label = QtWidgets.QLabel(self.centralwidget)
        self.Author_label.setGeometry(QtCore.QRect(330, 400, 467, 16))
        self.Author_label.setObjectName("Author_label")
        self.Author_Email_label = QtWidgets.QLabel(self.centralwidget)
        self.Author_Email_label.setGeometry(QtCore.QRect(330, 420, 151, 16))
        self.Author_Email_label.setObjectName("Author_Email_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Assistant Long Ear"))
        self.Path_start_label.setText(_translate("MainWindow", "Введите путь до аудиофайла формата WAV:"))
        self.File_input_button.setText(_translate("MainWindow", "Browse..."))
        self.Path_result_lable.setText(_translate("MainWindow", "Укажите папку для сохранения результата:"))
        self.File_output_button.setText(_translate("MainWindow", "Browse..."))
        self.Label_filename_output.setText(_translate("MainWindow", "Укажите имя файла результата (без указания расширения):"))
        self.Calculate_button.setText(_translate("MainWindow", "Начать перевод из аудио в текст"))
        self.Finish_label.setText(_translate("MainWindow", "Статус"))
        self.Author_label.setText(_translate("MainWindow", "Created by Lazarev Pavel"))
        self.Author_Email_label.setText(_translate("MainWindow", "E-mail:  kymarimka@gmail.com"))
